materias = []

def cargaDeMaterias():
    materias.append([1,1, "Fundamentos de Informática"])
    materias.append([1,1, "Sistemas de Información I"])
    materias.append([1,1, "Pensamiento Crítico y Comunicación"])
    materias.append([1,1, "Teoría de Sistemas"])
    materias.append([1,1, "Elementos de Álgebra y Geometría"])
    materias.append([1,2, "Programación I"])
    materias.append([1,2, "Sistemas de Representación"])
    materias.append([1,2, "Matemática Discreta"])
    materias.append([1,2, "Fundamentos de Química"])
    materias.append([1,2, "Arquitectura de Computadores"])
    materias.append([1,2, "Álgebra"])
    materias.append([2,1, "Programación II"])
    materias.append([2,1, "Sistemas de Información II"])
    materias.append([2,1, "Sistemas Operativos"])
    materias.append([2,1, "Física I"])
    materias.append([2,1, "Cálculo I"])
    materias.append([2,2, "Programación III"])
    materias.append([2,2, "Paradigma Orientado a Objetos"])
    materias.append([2,2, "Fundamentos de Telecomunicaciones"])
    materias.append([2,2, "Ingeniería de Datos I"])
    materias.append([2,2, "Cálculo II"])
    materias.append([3,1, "Proceso de Desarrollo de Software"])
    materias.append([3,1, "Seminario de Integración Profesional"])
    materias.append([3,1, "Teleinformática y Redes"])
    materias.append([3,1, "Ingeniería de Datos II"])
    materias.append([3,1, "Probabilidad y Estadística"])
    materias.append([3,1, "Examen de Inglés"])
    materias.append([3,2, "Aplicaciones Interactivas"])
    materias.append([3,2, "Ingeniería de Software"])
    materias.append([3,2, "Física II"])
    materias.append([3,2, "Teoría de la Computación"])
    materias.append([3,2, "Estadística Avanzada"])
    materias.append([4,1, "Desarrollo de Aplicaciones I"])
    materias.append([4,1, "Dirección de Proyectos Informáticos"])
    materias.append([4,1, "Ciencia de Datos"])
    materias.append([4,1, "Seguridad e Integridad de la Información"])
    materias.append([4,1, "Modelado y Simulación"])
    materias.append([4,2, "Desarrollo de Aplicaciones II"])
    materias.append([4,2, "Evaluación de Proyectos Informáticos"])
    materias.append([4,2, "Inteligencia Artificial"])
    materias.append([4,2, "Tecnología y Medio Ambiente"])
    materias.append([4,2, "Práctica Profesional Supervisada"])
    materias.append([4,2, "Optativa 1"])
    materias.append([5,1, "Arquitectura de Aplicaciones"])
    materias.append([5,1, "Tendencias Tecnológicas"])
    materias.append([5,1, "Proyecto Final de Ingeniería en Informática"])
    materias.append([5,1, "Calidad de Software"])
    materias.append([5,1, "Optativa 2"])
    materias.append([5,2, "Negocios Tecnológicos"])
    materias.append([5,2, "Tecnología e Innovación"])
    materias.append([5,2, "Derecho Informático"])
    materias.append([5,2, "Optativa 3"])
    
    return materias
    
